config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "static_pages#index"
  resources :static_pages, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @render_result = params[:search]

    if @render_result
      flickr = Flickr.new ENV["key"], ENV["secret"]
      @photos = flickr.photos.search :user_id => static_pages_params[:id]
    end
  end

  def static_pages_params
    params.require(:search).permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoFeedApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Home</h1>

<%= form_with(scope: :search, url: static_pages_path, method: "get") do |form| %>
    <%= form.text_field :id %>
    <%= form.submit %>
<% end %>

<% if @render_result %>
   <% @photos.each do |photo| %>
        <img src="<%= Flickr.url(photo) %>">
    <% end %>
<% end %>